[package]
name = "huione_test_utils"
version = "0.2.0"
authors = ["HUIONE Maintainers <maintainers@huione.com>"]
edition = "2018"
publish = false

[dependencies]
libc = "0.2"
huione_rbpf = { path = "../" }
